apiVersion: v1
kind: Service
metadata:
  name: react-java-dataset-app
  labels:
    app: react-java-dataset-app 
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30091
    name: http  
  selector:
    app: react-java-dataset-app